defaults:
    - data: imagenet-mini
    - experiment: exp_test

paths:
  raw_data_path: "data/raw/"
  processed_data_path: "data/processed/"
  external_data_path: "data/raw/"
  visual_path: "reports/figures/"
  model_path: "models/"
  log_path: "logs/"
  profile_path: "profiles/"

hydra:
  job:
    chdir: False

wandb:
  entity: "02476-mlops-group7"
  project: "mlops-project"
  log_model: True
  log_freq: 20
