model: resnest50d

batch_size: 32
max_epochs: 50
max_steps: -1
val_check_interval: 0.25
limit_val_batches: 1
num_sanity: 0
precision: bf16

momentum: 0.9
decay: 0.0001
lr: 0.1
lr_monitor: val_loss
lr_mode: min
lr_patience: 3
lr_decay: 0.5
lr_threshold: 0.0001

monitor: val_accuracy
monitor_mode: max
es_patience: 20

log_freq: 20
check_every_n_epoch: 1

criterion: NLLLoss
optimizer: SGD
scheduler: ReduceLROnPlateau

hydra:
  job:
    chdir: False