model: resnest50d

lr: 0.01
momentum: 0.9
decay: 0.001

criterion: NLLLoss
optimizer: SGD
scheduler: ReduceLROnPlateau

hydra:
  job:
    chdir: False

paths:
  processed_data_path: "data/processed/"
  model_path: "models/"
