name: Docker Image CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag docker.io/${{ secrets.DOCKER_HUB_REPOSITORY }}/train:$GITHUB_SHA
          docker push docker.io/${{ secrets.DOCKER_HUB_REPOSITORY }}/train:$GITHUB_SHA
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: docker.io/${{ secrets.DOCKER_HUB_REPOSITORY }}/train:$GITHUB_SHA
